name: port_karo
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.9.0
  geolocator: ^12.0.0
  http:
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  another_flushbar: ^1.12.30
  url_launcher: ^6.3.1
  share_plus: ^10.1.3
  curved_navigation_bar:
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.1
  permission_handler:
  app_settings:
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
      - assets/

  fonts:
    - family: poppins_regular
      fonts:
        - asset: fonts/poppins_regular.ttf
    - family: roboto_regular
      fonts:
        - asset: fonts/roboto_regular.ttf
    - family: kanit_regular
      fonts:
        - asset: fonts/kanit_regular.ttf
    - family: poppins_black
      fonts:
        - asset: fonts/poppins_black.ttf
    - family: protestRiot_regular
      fonts:
        - asset: fonts/protestRiot-regular.ttf
    - family: bold.otf
      fonts:
        - asset: fonts/sf_pro/bold.otf
    - family: medium.otf
      fonts:
        - asset: fonts/sf_pro/medium.otf
    - family: regular.otf
      fonts:
        - asset: fonts/sf_pro/regular.otf
    - family: light_italic.otf
      fonts:
        - asset: fonts/sf_pro/light_italic.otf


